package Formularios;
import Clases.ClaseCuenta;
import static Clases.Cuenta.c;
import javax.swing.JOptionPane;
/**
 *
 * @author Julio Vargas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIniciarSesión = new javax.swing.JLabel();
        lblExclusivo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblConstraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pfContraseña = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnIngresar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblIniciarSesión.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        lblIniciarSesión.setText("Iniciar Sesión");
        getContentPane().add(lblIniciarSesión);
        lblIniciarSesión.setBounds(150, 10, 240, 70);

        lblExclusivo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblExclusivo.setText("Solo los usuarios exclusivos pueden ingresar");
        getContentPane().add(lblExclusivo);
        lblExclusivo.setBounds(150, 60, 260, 30);

        lblUsuario.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(160, 90, 80, 40);

        lblConstraseña.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        lblConstraseña.setText("Contraseña:");
        getContentPane().add(lblConstraseña);
        lblConstraseña.setBounds(150, 140, 90, 30);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(240, 90, 240, 40);
        getContentPane().add(pfContraseña);
        pfContraseña.setBounds(240, 140, 240, 40);

        btnRegistrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrarse");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(250, 190, 120, 30);

        btnIngresar1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnIngresar1.setText("Ingresar");
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar1);
        btnIngresar1.setBounds(390, 190, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/acceso (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 130, 130);

        setSize(new java.awt.Dimension(530, 271));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

       RegistroAdmin r = new RegistroAdmin();
       r.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        // TODO add your handling code here:
        String esp = "";
        
        
        
        char [] password = pfContraseña.getPassword();
        for(int i = 0; i < password.length ; i++){

            esp+= password[i];
        }
        int  r = ClaseCuenta.BuscarUsuario(txtUsuario.getText(),esp);
        if(r != -1){
            Interfaz i = new Interfaz();
            i.in =r;
            i.setVisible(true);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null,"Bienvenido "+ c.get(0).getNombre() + " " + c.get(0).getApellido() +
                "\nIngresó al sistema como Administrador");
        }
        
       
        else{
            JOptionPane.showMessageDialog(null,"Usuario/Constraseña incorrecta.");
        }
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConstraseña;
    private javax.swing.JLabel lblExclusivo;
    private javax.swing.JLabel lblIniciarSesión;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pfContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
